# -*- mode: ruby -*-
# vi: set ft=ruby :
### Copyright 1999-2020. Plesk International GmbH.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "plesk/plesk-latest"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.name = "plesk-latest"
  end

  config.ssh.insert_key = false

  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 8880, host: 8880
  config.vm.network "forwarded_port", guest: 80, host: 1080
  config.vm.network "forwarded_port", guest: 433, host: 10443
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 8447, host: 8447

  config.vm.provision "shell", path: "../scripts/install_updates.sh"
  config.vm.provision "shell", path: "../scripts/set_admin_password.sh"
end
